name: Regular Pull Request
description: Create a PR to change some code in this repo

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this pull request! Try to include as much information as you can.
  - type: markdown
    attributes:
      value: |
        WEB-?

        ## Changes
        <!-- List high-level changes that are included in the PR -->
        - ?

        ## QA
        <!-- List QA steps to reproduce changes affected in the PR -->
        - ?

        <!-- If appropriate, list relevant E2E tags here -->
        **E2E Tags:** <!-- addToCart, cart, category, checkout, invoice, login, logout, orderHistory, returns, payment, search, price, commandments, regression, accountSignup, cartMenu, showcase, cadCam, autoPay -->
        
        ## Deployment
        ### DbUp Scripts
        
  - type: checkboxes
    attributes:
      label: |
        Before opening, please confirm:
      options:
        - label: I certify that I do not have any DbUp Scripts associated with this PR
          required: true
        - label: I certify that I do not have any Oracle Changes associated with this PR
          required: true
        - label: I certify that I have no other steps that need to take place before or after this PR is deployed
          required: true
